###posts requests

###Request1
POST http://localhost:3000/posts
Content-Type: application/json

{
  "title": "rdr2",
  "content": " good game"
}

###Request2
GET http://localhost:3000/posts


###Request3
PUT http://localhost:3000/posts/5
Content-Type: application/json

{
  "title": "ismael",
  "content": "best in the world"
}

###request4
DELETE http://localhost:3000/posts/8

###request5
GET http://localhost:3000/posts/limit/5/offset/8


###request6
GET http://localhost:3000/posts/search?title=lebb





###comments requests


###Request1
GET http://localhost:3000/comments


###Request2
POST http://localhost:3000/comments
Content-Type: application/json

{
  "postId": 16,
  "text": "helloooo"
}


###request3
PUT http://localhost:3000/comments/5
Content-Type: application/json

{
  "text": "letsgooo"
}

###request4
DELETE http://localhost:3000/comments/4






